# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b86ebe11b9bb4ffce85df442419e644aa8abffdd384a7220646b606b7046640ae9ef932878604ae2633c124fe8a15deb300e00c913e167cd656722d55a7f997

test:
  secret_key_base: e239198e60f31222fcddda69c7ce0c1b5bd6e1a2b49b089337041b2f1155cffc4ce0fa41030705634eb1e3672cec336909c9f82c7e0d8e51a06d866b797a70a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
